-- ============================================================
-- AJUSTES 2026-09-10 (5) · Estado de resultados ene–jul 2026 y capacidades de planta (hoja de Mauricio, 10-sep tarde)
-- Corrige Financiero (mercadeo era 3,7%, no 0,3%; pérdidas y gastos financieros), Operaciones (qué más puede fabricar) y el caso. Idempotente.
-- ============================================================
update pilares set enunciado = '¿Cómo aguantar hasta febrero con la venta a la mitad? ¿Qué gasto se puede pausar o volver variable sin romper la operación? ¿De dónde sale caja rápida sin endeudarse más? Datos: el equilibrio está cerca de $250M/mes; de mayo a agosto se vendieron $153M/mes. La estructura es casi toda fija: el costo de producción pasó de ~64% de la venta (enero–abril) a más del 100% en mayo y julio. Enero–julio de 2026 deja pérdida operativa de $76M y neta de $178M; los gastos financieros son ~$15M/mes. Publicidad es 3,7% de la venta (11% con su personal). El margen sobre costo directo de los impermeables es alto (55–65%); el de las líneas institucionales, bajo. Hay deuda financiera y la caja alcanza para pocos meses.' where sesion_id = 'impercap' and nombre = 'Financiero';
update pilares set enunciado = replace(enunciado, 'Unas 25 referencias: impermeables, ponchos, gabanes, botas, delantales y batas. Logística de dos personas.', 'Unas 25 referencias: impermeables, ponchos, gabanes, botas, delantales y batas. Hoy también puede fabricar pijamas para carro, moto de carga, bicicleta y lavadora, portacascos, pantalones, capa para mascota, bolsas de empaque personalizadas, estampado de tela y delantales infantiles. Logística de dos personas.') where sesion_id = 'impercap' and nombre = 'Operaciones';
update sesiones set config = jsonb_set(config, '{caso}', to_jsonb(replace(config->>'caso', '$153M/mes frente a ~$250M que necesita para cubrir sus costos, con 37 personas en nómina y la caja para pocos meses.', '$153M/mes frente a ~$250M que necesita para cubrir sus costos; enero a julio ya acumula pérdidas por $178M, con 37 personas en nómina y la caja para pocos meses.'))) where id = 'impercap';
select nombre, left(enunciado, 90) as enunciado from pilares where sesion_id = 'impercap' and nombre in ('Financiero','Operaciones');
select config->>'caso' as caso from sesiones where id = 'impercap';
