-- ============================================================
-- AJUSTES 2026-09-10 (4) · Enunciados de los 5 pilares: pregunta primero, sin el plan de Mauricio ni datos sensibles
-- Aprobados por Daniel el 10-sep. Idempotente.
-- ============================================================

update pilares set enunciado = '¿Cómo inyectar ventas en los próximos 3 a 6 meses mientras no llueve en Antioquia? ¿A quién le sigue lloviendo y cómo llegar allá rápido? ¿Qué le podemos vender al cliente que ya nos compra, aunque no sea impermeable? Datos: 2025 cerró en $2.734M (+50%); enero a abril de 2026 iba +32% y de mayo a agosto cayó 40%, a $153M/mes. Antioquia es el 61% de las unidades, Bogotá 9%, el Pacífico casi nada. Dos cuentas grandes son cerca del 40% de la venta. Unos 500 clientes atendidos por un vendedor, una auxiliar y un practicante.' where sesion_id = 'impercap' and nombre = 'Mercadeo y Ventas';
update pilares set enunciado = '¿Cómo aguantar hasta febrero con la venta a la mitad? ¿Qué gasto se puede pausar o volver variable sin romper la operación? ¿De dónde sale caja rápida sin endeudarse más? Datos: el equilibrio está cerca de $250M/mes y de mayo a agosto se vendieron $153M/mes. El personal pasó de pesar ~30% de la venta a ~50%; mercadeo es 0,3%. El margen de los impermeables sobre su costo directo es alto, entre 55 y 65%; el de las líneas institucionales es bajo. Hay deuda financiera y la caja alcanza para pocos meses.' where sesion_id = 'impercap' and nombre = 'Financiero';
update pilares set enunciado = '¿Cómo reorganizar 37 personas para vender más con la misma nómina? ¿Quién de planta podría estar hoy vendiendo, atendiendo clientes o despachando? ¿Cómo activar ideas y compromiso del equipo en plena crisis? Datos: estructura transversal, no piramidal: 24 operarios, coordinador de producción, líder de operaciones, dos de logística, líder general, líder de mercadeo, una auxiliar administrativa comercial, un vendedor, un practicante y una auxiliar administrativa. El brazo comercial son cuatro personas para unos 500 clientes y se debilitó este año.' where sesion_id = 'impercap' and nombre = 'Estructura y Cultura';
update pilares set enunciado = '¿Qué se puede fabricar o hacer con media planta parada? ¿Qué maquila, producto o servicio cabe en la capacidad y el material que ya tenemos? ¿Cómo bajar el costo por unidad sin sacrificar calidad? Datos: planta en Medellín con 24 operarios y materia prima de plástico 100% reciclado. En abril despachó 56.000 unidades; de mayo a agosto, 28.000 al mes. Unas 25 referencias: impermeables, ponchos, gabanes, botas, delantales y batas. Logística de dos personas.' where sesion_id = 'impercap' and nombre = 'Operaciones';
update pilares set enunciado = '¿Qué alianza, contacto o idea rara podría mover la aguja y no cabe en los otros pilares? ¿Con quién deberíamos hablar la próxima semana? Aquí van contactos concretos, alianzas, canales inesperados y obviedades que nadie ha dicho.' where sesion_id = 'impercap' and nombre = 'Otros';

select orden, nombre, left(enunciado, 80) as enunciado from pilares where sesion_id = 'impercap' order by orden;
