-- ============================================================
-- SESIÓN: Foro Impercap · viernes 11-sep-2026, 2:00 pm, Estrella Estéreo
-- CAMBIAR las claves antes de correr.
-- ============================================================
insert into sesiones (id, nombre, empresa, facilitador, etapa, clave_admin, clave_lider, config) values
('impercap', 'Foro de ideación · Impercap', 'Impercap', 'Daniel Restrepo', 'bienvenida', 'impercap2026', 'pilar2026',
 '{"votos_por_pilar": 3, "minutos_ideacion": 10, "minutos_matriz": 8, "minutos_pausa": 5, "caso": "Impercap (Impermeables Vélez y Forero SAS) lleva más de 10 años fabricando impermeables para moto en plástico reciclado en Medellín. En 2025 vendió $2.734M (+50%) y enero–abril de 2026 iba +32%. Con El Niño, de mayo a agosto la venta cayó 40%: $153M/mes frente a ~$250M que necesita para cubrir sus costos, con 40 personas en nómina y la caja para pocos meses. El reto del foro: ideas que den ventas y aire financiero en los próximos 3 a 6 meses, desde Mercadeo y Ventas, Financiero, Estructura y Cultura, Operaciones y Otros.", "restricciones": ["Caja limitada: no hay flujo para indemnizar ni para contratar sin retorno rápido", "Un vendedor tarda ~3 meses en volverse rentable", "El clima vuelve a favor ~febrero: el corto plazo es sobrevivir y llegar al punto de equilibrio", "Puede haber activos vendibles o una línea de crédito: preguntar antes de asumir"], "escala_max": 5}'::jsonb)
on conflict (id) do update set nombre = excluded.nombre, config = excluded.config;

delete from pilares where sesion_id = 'impercap';
insert into pilares (sesion_id, orden, nombre, icono, color, enunciado, subfrentes) values
('impercap', 1, 'Mercadeo y Ventas', 'fa-bullhorn', 'blue',
 'Ventas 2025: $2.734M (+50% vs 2024), promedio $228M/mes. Ene–abr 2026 iban +32%; con El Niño, may–ago cayeron 40% ($153M/mes; julio $112M) y las unidades 34%. Mezcla: estaciones de servicio ~35%, distribuidores y clientes varios ~55%, retail ~5%, tiendas de motos ~3%, ferreterías ~1%. Muy concentrada: Grupo Éxito/EDS (vía Promotora de Comercio Social) y Distracom son ~40% de 2026; Antioquia es el 61% de las unidades, Bogotá 9%, Valle 1%. Precio promedio ~$5.300; ~500 clientes activos atendidos por 1 vendedor, 1 auxiliar y un practicante. ¿Cómo inyectar ventas en los próximos 3–6 meses?',
 '["Cobertura geográfica", "Diversificación de productos", "Desarrollo del cliente actual", "Clientes nuevos", "Canal digital / IA"]'),
('impercap', 2, 'Financiero', 'fa-coins', 'green',
 'Punto de equilibrio ~$250M/mes; may–ago 2026 vendió $153M/mes. Con la venta a la mitad, el costo de personal pasó de ~30% a ~50% de las ventas; mercadeo es 0,3%. Materia prima + mano de obra pesan ~52% de la venta (meta 2026: bajar 6 puntos, a 46%). Margen sobre costo directo de los impermeables principales: 56–67% (tradicional 56%, premium 57%, metalizado 58%, pijama 67%); delantales y batas institucionales solo 9–39%. Hay deuda bancaria (meta: reducirla 60%) y en el plan estaban reestructurar pasivos y buscar un socio de capital. ¿Cómo optimizar costos y gastos y financiar la travesía hasta que vuelva la lluvia (~febrero)?',
 '["Estructura de costos y gastos", "Caja y financiación", "Activos y capital de trabajo"]'),
('impercap', 3, 'Estructura y Cultura', 'fa-people-group', 'purple',
 '40 personas, estructura transversal (no piramidal): 27 operarios (68%), coordinador de producción, líder de operaciones (producción y logística), 2 de logística, líder general, líder de mercadeo y ventas, auxiliar comercial, 1 vendedor, practicante SENA de mercadeo y auxiliar administrativa; contabilidad, SGSST y diseño por prestación de servicios. El brazo comercial es de 4 personas para ~500 clientes y se debilitó (renunciaron 2 vendedoras y el de mercadeo). Valores declarados: respeto, honestidad, disciplina, compromiso, pasión; objetivo 2026: formar líderes con autonomía. ¿Cómo reorganizar el equipo y activar su capacidad de reinventarse? (Ej.: cofinanciar formación tipo Platzi 50/50.)',
 '["Fuerza comercial", "Roles y estructura", "Cultura y capacidad de reinvención"]'),
('impercap', 4, 'Operaciones', 'fa-gears', 'teal',
 'Planta en Medellín (El Chagualo) con 27 operarios; en 2026 llegó a despachar ~56.000 unidades/mes (abril) y en may–ago bajó a ~28.000/mes: la mitad de la planta está ociosa. Materia prima: plástico PEMD reciclado; en el plan 2026 estaban comprar una extrusora (materia prima propia) y una selladora, ciclos Kaizen y un espacio de I+D. Logística: 2 personas, inventario de seguridad objetivo 40.000 unidades, búsqueda de operadores logísticos. Portafolio de ~25 referencias: impermeables (tradicional, premium, metalizado, niño, pijama), ponchos, gabanes, botas, delantales y batas institucionales. ¿Cómo usar la planta, el equipo y los proveedores para bajar costos, fabricar otras cosas o servir a nuevos clientes?',
 '["Capacidad y planta", "Compras y proveedores", "Logística y entregas", "Calidad y procesos"]'),
('impercap', 5, 'Otros', 'fa-lightbulb', 'amber',
 'Dibujo libre: contactos, alianzas, ideas disruptivas u obviedades que no caben en los otros pilares. En el plan 2026 ya estaban: línea institucional para alimentos, ventas por Mercado Libre, CRM y atención por WhatsApp con IA, presencia en Bogotá y canales digitales.',
 '[]');
